#here we definewhich adapter to use for ActionCable
development:
  adapter: async

test:
  adapter: async

production:
  adapter: postgresql
  url: postgres://fnbmoydfyosuod:097f909f98d1fed83b51c4c9884c922569ab088e5bd99827b70662f5946a1ae7@ec2-54-235-173-161.compute-1.amazonaws.com:5432/d25cibj7fkcpre
